// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJhsPHBcDn0sEOZZ4KSQHMVpVOpTMcqQ',
    appId: '1:710081376465:web:5d074b4c21dfbe66d815f0',
    messagingSenderId: '710081376465',
    projectId: 'flutter-vakanuvis',
    authDomain: 'flutter-vakanuvis.firebaseapp.com',
    storageBucket: 'flutter-vakanuvis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAaJwF_po4BrUHEnq71fmCJBPLG7UcvJM',
    appId: '1:710081376465:android:e5ec2957ec78d8dbd815f0',
    messagingSenderId: '710081376465',
    projectId: 'flutter-vakanuvis',
    storageBucket: 'flutter-vakanuvis.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvJhsPHBcDn0sEOZZ4KSQHMVpVOpTMcqQ',
    appId: '1:710081376465:web:82d872abd74283aed815f0',
    messagingSenderId: '710081376465',
    projectId: 'flutter-vakanuvis',
    authDomain: 'flutter-vakanuvis.firebaseapp.com',
    storageBucket: 'flutter-vakanuvis.appspot.com',
  );

}